[package]
name = "dmfr"
version = "0.2.0"
description = "Transitland compatible Distributed Mobility Feed Registry schema"
license = "AGPL-3.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regress = "0.10"
